---

# Nginx confgiure

- name: Alfresco | Create or update the configurations for alfresco site
  template:
    src: alfresco.site.j2
    dest: "{{ nginx_dir }}/sites-available/{{ inventory_hostname }}"
    backup: true

- name: Alfresco | Enable alfresco sites
  file:
    path: "{{ nginx_dir }}/sites-enabled/{{ inventory_hostname }}"
    src: "{{ nginx_dir }}/sites-available/{{ inventory_hostname }}"
    state: link
  notify:
    - reload nginx

- name: Alfresco | Create or update the configurations for Alfresco site
  template:
    src: environment.j2
    dest: "/etc/environment"
    backup: true

# Alfresco config deploy

- name: Alfresco | Create or update the configurations for Alfresco tomcat app
  template:
    src: alfresco-global.properties.j2
    dest: "/usr/share/tomcat/shared/classes/alfresco-global.properties"
    backup: true
  notify:
    -  Alfresco | Restart tomcat

- name: Alfresco | Update tomcat catalina.properties
  template:
    src: catalina.properties.j2
    dest: /etc/tomcat/catalina.properties
    backup: true
  notify:
    -  Alfresco | Restart tomcat

- name: Alfresco | Update tomcat server.xml
  template:
    src: server.xml.j2
    dest: /etc/tomcat/server.xml
    backup: true
  notify:
    -  Alfresco | Restart tomcat

# Solr 4 config related updates

- name: Alfresco | Update tomcat tomcat-users.xml.j2
  template:
    src: tomcat-users.xml.j2
    dest: /etc/tomcat/tomcat-users.xml
    backup: true
  notify:
    -  Alfresco | Restart tomcat

- name: Alfresco | Enable tomcat service
  service:
    name: tomcat
    enabled: yes
  when: "{{ alfresco_service_enabled }}"
  notify:
    -  Alfresco | Restart tomcat

